# This workflow deploys the contents of the 'static' folder to an AWS S3 bucket

name: Deploy Static Website to AWS S3

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - master # This can be changed to any needed branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo content
      - name: Checkout repository
        uses: actions/checkout@v3

      # Sync files with S3
      # This action uses the AWS CLI so no credentials are hardcoded.
      - name: Sync static folder to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "static"
